name: zeronet
version: 0.5.1-r1758
icon: icon.png
summary: Open, free and uncensorable websites
description: |
  Decentralized websites using Bitcoin crypto and the BitTorrent network - https://zeronet.io
  Why?
  We believe in open, free, and uncensored network and communication.
  No single point of failure: Site remains online so long as at least 1 peer is serving it.
  No hosting costs: Sites are served by visitors.
  Impossible to shut down: It's nowhere because it's everywhere.
  Fast and works offline: You can access the site even if Internet is unavailable.

plugs:
  network:
  network-bind:

grade: stable
confinement: strict

apps:
  zeronet:
    command: launcher.py
    plugs: [network,network-bind]
parts:
  bundle:
    after:
      - source
    source: bundle
    plugin: python
    python-version: python2
    requirements: requirements.txt
  source:
    source: https://github.com/HelloZeroNet/ZeroNet
    source-branch: master
    source-type: git
    snap:
      - src
      - tools
      - plugins
      - zeronet.py
      - start.py
    plugin: dump
  scripts:
    source: scripts
    after:
      - bundle
    snap:
      - launcher.py
    plugin: dump
