name: zeronet
version: 0.5.3-r2002
summary: Open, free and uncensorable websites
description: |
  Decentralized websites using Bitcoin crypto and the BitTorrent network - https://zeronet.io
  Why?
  We believe in open, free, and uncensored network and communication.
  No single point of failure: Site remains online so long as at least 1 peer is serving it.
  No hosting costs: Sites are served by visitors.
  Impossible to shut down: It's nowhere because it's everywhere.
  Fast and works offline: You can access the site even if Internet is unavailable.

grade: stable
confinement: strict

apps:
  zeronet:
    command: launcher.py
    plugs: [network,network-bind]
  tor:
    command: tor.py
    plugs: [network,network-bind]
parts:
  bundle:
    prime:
      - usr
      - bin
      - lib
      - include
      - etc
      - -usr/share/doc
      - -usr/share/man
    source: bundle
    plugin: python
    python-version: python2
    requirements: requirements.txt
  source:
    source: https://github.com/HelloZeroNet/ZeroNet
    source-branch: master
    source-type: git
    organize:
      update.py: unused.update.py
      update.pyc: unused.update.pyc
    prepare: |
      sed 's/self.plugin_path = "plugins"/self.plugin_path = os.environ["SNAP_USER_COMMON"]+"\/plugins"/g' -i src/Plugin/PluginManager.py
      python2 -m py_compile $(find -type f -iname "*.py" -print)
    prime:
      - src
      - tools
      - plugins
      - zeronet.py
      - zeronet.pyc
      - start.py
      - start.pyc
    plugin: dump
  scripts:
    source: scripts
    after:
      - bundle
      - source
    prime:
      - launcher.py
      - tor.py
      - torrc
      - update.py
    plugin: dump
    prepare: |
      python2 -m py_compile $(find -type f -iname "*.py" -print)
  tor:
    source: https://git.torproject.org/tor.git
    source-tag: tor-0.2.9.10
    source-type: git
    plugin: autotools
    configflags: [--disable-asciidoc]
    build-packages:
      - git
      - build-essential
      - automake
      - libevent-dev
      - libssl-dev
