name: zeronet
version: 0.5.1-r0
summary: Open, free and uncensorable websites, using Bitcoin and BitTorrent
description: |
  Decentralized websites using Bitcoin crypto and the BitTorrent network - https://zeronet.io
  Why?
  We believe in open, free, and uncensored network and communication.
  No single point of failure: Site remains online so long as at least 1 peer is serving it.
  No hosting costs: Sites are served by visitors.
  Impossible to shut down: It's nowhere because it's everywhere.
  Fast and works offline: You can access the site even if Internet is unavailable.

plugs:
  network:
  network-bind:

grade: stable
confinement: strict

apps:
  zeronet:
    command: zero/Python/python $SNAP/main.py
    plugs: [network,network-bind]
  env:
    command: env
parts:
  bundle:
    source: https://github.com/HelloZeroNet/ZeroBundle/raw/master/dist/ZeroBundle-linux64.tar.gz
    plugin: dump
    snap:
      - zero
      - LICENSE
    organize:
      ssl: zero/ssl
      Python: zero/Python
      lib: zero/lib
      LICENSE.txt: LICENSE
  source:
    source: https://github.com/HelloZeroNet/ZeroNet
    source-branch: master
    source-type: git
    snap:
      - src
      - tools
      - plugins
      - zeronet.py
      - start.py
    plugin: dump
  scripts:
    source: scripts
    plugin: dump
    snap:
      - main.py
