name: zeronet
version: 0.0.1
summary: Open, free and uncensorable websites, using Bitcoin and BitTorrent
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
#  zeronet:
#    command: usr/bin/python3 $SNAP/zeronet/zeronet.py
  zeronet:
    command: bash $SNAP/zero/ZeroNet.sh
    plugs: [network,network-bind]
  env:
    command: env
#    daemon: simple
parts:
#  py:
#    plugin: python
#    stage-packages:
#      - python3
#      - python3-gevent
#  code:
#    after:
#      - py
#    source: https://github.com/HelloZeroNet/ZeroNet
#    source-branch: master
#    source-type: git
#    plugin: dump
#    organize:
#      .: zeronet
  bundle:
    source: https://github.com/HelloZeroNet/ZeroBundle/raw/master/dist/ZeroBundle-linux64.tar.gz
    plugin: dump
    snap:
      - zero
      - LICENSE
    organize:
      ssl: zero/ssl
      Python: zero/Python
      lib: zero/lib
      LICENSE.txt: LICENSE
  source:
    source: https://github.com/HelloZeroNet/ZeroNet
    source-branch: master
    source-type: git
    snap:
      - zeronet
    plugin: dump
    organize:
      src: zeronet/src
      tools: zeronet/tools
      plugins: zeronet/plugins
      zeronet.py: zeronet/zeronet.py
      start.py: zeronet/start.py
  scripts:
    source: scripts
    plugin: dump
    snap:
      - zero
    organize:
      zeronet.sh: zero/ZeroNet.sh
#  deb:
#    plugin: nil
#
#    filesets:
#      python:
#        - usr/bin/python*
#        - lib
#        - usr/lib
#    snap:
#      - $python
